### ISSUE TITLE
`Expected one matching path for '/home/dpc/.cargo/registry/src/github.com-*'!`

### ISSUE THREAD

**Issue by dpc** [dan-t/rusty-tags#10]
Hi,

No matter which project I try, I get:

% rusty-tags vi
Fetching source of dependencies ...
Expected one matching path for '/home/dpc/.cargo/registry/src/github.com-*'!

I don't seem to have `~/.cargo/registry/`

**Comment by dan-t** [comment]
Hi,

what are you getting for:
ls -la ~/.cargo/
cargo --version
rustc --version

Are you able to build your project with 'cargo build'?
Does 'rusty-tags vi' work after calling 'cargo build'?

Greetings,
Daniel

**Comment by dpc** [comment]
```
[futex:rust/mgit] (master)% ls -la ~/.cargo/
total 0
drwxrwxr-x. 1 dpc dpc   24 Jul 29 12:29 .
drwx------. 1 dpc dpc 3798 Nov 25 10:16 ..
drwxrwxr-x. 1 dpc dpc   22 Apr 20  2015 git
-rw-rw-r--. 1 dpc dpc    0 Jul 29 12:29 .nobackup
[futex:rust/mgit] (master)% cargo --version
cargo 0.7.0-nightly (79cb82d 2015-11-24)
[futex:rust/mgit] (master)%  rustc --version
rustc 1.6.0-nightly (a9d15a6e9 2015-11-23)
```

Yes, I am able to build it, and rusty-tags does not work after building.

**Comment by dan-t** [comment]
Can you check if the cargo from the stable release (cargo 0.5.0-nightly (833b947 2015-09-13)) behaves differently?

What is below ~/.cargo/git/ ?

What is the output of `cat Cargo.toml` ?

**Comment by dpc** [comment]
```
% tree -a ~/.cargo/    
/home/dpc/.cargo/
├── git
│   ├── checkouts
│   │   └── libcore-git.rs-009c2cd1d9d60148
│   │       └── master
│   │           ├── build.rs
│   │           ├── Cargo.toml
│   │           ├── .git
│   │           │   ├── config
│   │           │   ├── description
│   │           │   ├── HEAD
│   │           │   ├── hooks
│   │           │   │   └── README.sample
│   │           │   ├── index
│   │           │   ├── info
│   │           │   │   └── exclude
│   │           │   ├── logs
│   │           │   │   ├── HEAD
│   │           │   │   └── refs
│   │           │   │       ├── heads
│   │           │   │       │   └── master
│   │           │   │       └── remotes
│   │           │   │           └── origin
│   │           │   │               └── master
│   │           │   ├── objects
│   │           │   │   ├── info
│   │           │   │   └── pack
│   │           │   │       ├── pack-c690b63fb71f3d7e1a69245eab45b9f5fb651577.idx
│   │           │   │       └── pack-c690b63fb71f3d7e1a69245eab45b9f5fb651577.pack
│   │           │   └── refs
│   │           │       ├── heads
│   │           │       │   └── master
│   │           │       ├── remotes
│   │           │       │   └── origin
│   │           │       │       └── master
│   │           │       └── tags
│   │           └── README.md
│   └── db
│       └── libcore-git.rs-009c2cd1d9d60148
│           ├── config
│           ├── FETCH_HEAD
│           ├── HEAD
│           ├── hooks
│           ├── info
│           ├── objects
│           │   ├── info
│           │   └── pack
│           │       ├── pack-c690b63fb71f3d7e1a69245eab45b9f5fb651577.idx
│           │       └── pack-c690b63fb71f3d7e1a69245eab45b9f5fb651577.pack
│           └── refs
│               ├── heads
│               │   └── master
│               └── tags
└── .nobackup
```

Stable cargo does not seem to help.

```
% cargo --version
cargo 0.5.0-nightly (833b947 2015-09-13)
```

**Comment by dan-t** [comment]
Ok, can I see your 'Cargo.toml' ?

If it's this one 'https://github.com/dpc/libcore-git.rs/blob/master/Cargo.toml', then
I see the issue, your using local dependencies which currently aren't supported.

The other issue is, that you don't seem to have installed any git or crates.io
dependency and therefore the directories are missing.

So it's better that I don't expect these directories.

**Comment by dpc** [comment]
No, that's not the one.

https://github.com/dpc/colerr/blob/master/Cargo.toml

is one of couple that I've tried. Should that one work?

**Comment by dan-t** [comment]
On Wed, Nov 25, 2015 at 03:19:19PM -0800, Dawid Ciężarkiewicz wrote:
> No, that's not the one.
> 
> https://github.com/dpc/colerr/blob/master/Cargo.toml
> 
> is one of couple that I've tried. Should that one work?

Yes.

If you've build this cargo project, why isn't there
any of its dependencies contained anywhere in `~/.cargo` ?

**Comment by dpc** [comment]
Are you using multirust? Because the needed files seem to be sitting in `/home/dpc/.multirust/toolchains/*/cargo/` for me.

**Comment by dan-t** [comment]
On Thu, Nov 26, 2015 at 12:35:29PM -0800, Dawid Ciężarkiewicz wrote:
> Are you using multirust? Because the needed files seem to be sitting in /home/
> dpc/.multirust/toolchains/*/cargo/ for me.

Ok, I just wanted to ask if you're using multirust ;).
No, I haven't used multirust yet.

So under '~/.multirust/toolchains/*/cargo/' there's the
directory structure I'm expecting, right?

Do you know how multirust tells cargo where it should put its stuff?

Reading 'https://github.com/brson/multirust', it seems that there're
some wrapper scripts for rustc and cargo, so it might be not that
easy for tools like rusty-tags to get the necessary information.

**Comment by dan-t** [comment]
`rusty-tags 0.6.1` should now support multirust.
