### ISSUE TITLE
Empty (but present) dependencies table in `Cargo.toml` leads to error

### ISSUE THREAD

**Issue by ExpHP** [dan-t/rusty-tags#12]
Running rusty-tags on a crate with the following `Cargo.toml`:

    [package]
    name = "sparse"
    version = "0.1.0"
    authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]
    
    [dependencies]

Produces the error:

    Couldn't get Array of Tables entry for 'package'!

Removing the `[dependencies]` section (or adding an item to it) eliminates the error.
This is the issue that #11 was attempting to address.

**Comment by dan-t** [comment]
Thanks!

Should be fixed with `rusty-tags 0.6.1`.
