### ISSUE TITLE
Path Dependancies

### ISSUE THREAD

**Issue by tbelaire** [dan-t/rusty-tags#13]
I have separated my project into a few different crates the live side by side, with a path dependancy
Ex:
```
[dependencies]
gba = {path = "../gba"}
```

And it doesn't seem like it's picked up the tags.  How would I invoke it to get rusty-tags to nap those dependancies too?

I have them all in the same git repository, since I want to keep them in sync, and do *not* want to use git submodules, otherwise I'd use a `file://` git dep.

**Comment by dan-t** [comment]
That's a local path dependency that currently isn't supported.

Can you use a git dependency instead, something like:

    [dependencies.gba]
    git = "https://github.com/tbelaire/gba"

I can really understand not to like `git submodules` ;), but there's also `git subrepo[1]`
which is quite nice to work with.

[1] https://github.com/ingydotnet/git-subrepo

**Comment by dan-t** [comment]
I just pushed a first prototypical implementation supporting path dependencies.
It's contained in the `path_dependencies` branch.

This does only support first level path dependencies, so if you have
a path dependency and inside of it another path dependency, then
this second level path dependency won't be considered.

I don't quite like this solution, but supporting more than first level
path dependencies would involve a bigger change.

**Comment by tbelaire** [comment]
Cool, it works pretty well.  This is sufficient for my needs.  Thanks.
