### ISSUE TITLE
Flag to force regenerate

### ISSUE THREAD

**Issue by tbelaire** [dan-t/rusty-tags#14]
I was playing around with it, and I would like to have a flag `--force-rebuild` that forced a rebuild of all the files, and doesn't trust the cache.  The use case for this was that I was recompiling rusty-tags and wanted to see if the new changes changed anything. (Changing how `consts` are matched).

Right now I'm just doing `rm -rf ~/.rusty-tags` and then `rm`ing any I know about, but I'm sure I'm missing some.

Alternatively, you could check the timestamp on `rusty-tags`, and if the files are older than the executable, rebuild them.  That would also solve my problem.

**Comment by dan-t** [comment]
rusty-tags 0.6.4 now has a '--force-recreate' flag
