### ISSUE TITLE
Record enum variants.

### ISSUE THREAD

**Issue by tbelaire** [dan-t/rusty-tags#16]
It would be nice if we could jump to enum variants. I'm not sure how you'd match the line with a regex however.

**Comment by dan-t** [comment]
I don't think that it's possible to write a regex that's independent of the number of variants.

As a workaround you could write several regexes that match a certain number of variants.
So one regex matching the first variant, one matching the second ...

**Comment by dan-t** [comment]
Perhaps the right way would be to leave ctags and use an other approach to create tags,
like getting the AST of a rust source file an generating the tags file from it.

Then you could quite easily handle the variants of an enum and also e.g. the fields of a struct.

**Comment by tbelaire** [comment]
Lets check the [rust spec][spec] on enums...
So, good news, it cannot have arbitrary nesting of `{}`s, only one level from struct like enums.  But, there can be arbitrary deep nesting of `<>` from types... :( But wait, we don't care, do we?

This regex can match just an enum (well, mostly, I think I need more newlines), even a struct enum.
But I don't know how you'd get different capture groups out of it.

    /enum.*(\n*([^{}]*|[^{}]*{[^}]*}))*}/

Ok, yeah, making the regex isn't that bad, it's making capture groups that's too hard.  :(

[spec]: https://doc.rust-lang.org/reference.html#enumerations

**Comment by dan-t** [comment]
On Thu, Dec 03, 2015 at 07:12:06AM -0800, Theo Belaire wrote:
> Ok, yeah, making the regex isn't that bad, it's making capture groups that's
> too hard. :(

That's what I meant with several regexes.

If you have an enum like:

    enum Foo {
       Baz { ... },
       Bar { ... },
       Boo { ... }
    }

Then you can define one regex capturing Baz, another capturing Bar
and a third capturing Boo.

It's a workaround and you can only support a fixed number of
variants. But perhaps just support 10 variants is already
enough for most cases.

**Comment by dan-t** [comment]
If you're using [universal-ctags](https://github.com/universal-ctags/ctags) then you're automatically getting tags for enum variants and also struct fields.
