### ISSUE TITLE
Support a scope operator

### ISSUE THREAD

**Issue by andrewcsmith** [dan-t/rusty-tags#18]
I've been hacking away at getting rusty-tags to work with tagbar, but the lack of a scope operator in the final output makes things difficult. Would it be possible to support a scoping of some sort in the tags? (At least a file-level scope?)

In the meantime, I can clean up the code I wrote to integrate with tagbar and add it to the wiki or something.

![screenshot 2015-12-13 11 52 14](https://cloud.githubusercontent.com/assets/378677/11768912/00c1ee36-a190-11e5-8297-40e8bdd3f048.png)

**Comment by dan-t** [comment]
`tagbar` needs the tags of the current file, which shouldn't be a performance
issue if they're created when the file is opened.

I don't know how customizable `tagbar` is, if you could give it options
for the `ctags` command, then you could take a look at the `create_tags`
function.

**Comment by andrewcsmith** [comment]
`tagbar` reads in from stdout, so I just made `rusty-tags` print the merged tags file to stdout and the tags showed up just fine.

I'm looking into this more today and it looks like it's [impossible to work with scope in regex matches](http://stackoverflow.com/questions/15577876/can-i-add-scope-information-to-tags-generated-with-regex-lang-in-exuberant).Related: [How to Add Support for a New Language to Exuberant Ctags](http://ctags.sourceforge.net/EXTENDING.html)

Obviously this is outside of the scope (heh) of what rusty-tags does right now, so it's your call as to whether to close this issue or keep it on the radar. You've essentially written a chunk of the lexer already.

And hey, maybe the parser should be written in Rust!

**Comment by dan-t** [comment]
> tagbar reads in from stdout, so I just made rusty-tags print the merged tags
> file to stdout and the tags showed up just fine.

Aren't you getting then all tags displayed in the `tagbar` instead
of only the ones of the current file?

> And hey, maybe the parser should be written in Rust!

I certainly wouldn't want to write a parser for Rust, but using
the one from rustc - if it stablizes - getting an AST from
it and generating the tags from it might be an option.
