### ISSUE TITLE
SublimeText Support ?

### ISSUE THREAD

**Issue by Byron** [dan-t/rusty-tags#2]
This is a question, not an issue, and hopefully the easiest way to get in touch, publicly.

I am using Sublime Text, which supports tag files created via `ctags -R -f .tags` using the [CTags Plugin](https://github.com/SublimeText/CTags).

Is `rusty-tags` able to generate those as well ?

Thank you

**Comment by dan-t** [comment]
On Sun, Mar 08, 2015 at 09:21:01AM -0700, Sebastian Thiel wrote:
> This is a question, not an issue, and hopefully the easiest way to get in
> touch, publicly.
> 
> I am using Sublime Text, which supports tag files created via ctags -R -f .tags
> using the CTags Plugin.
> 
> Is rusty-tags able to generate those as well ?

In this case 'rusty-tags vi' should just work.

**Comment by Byron** [comment]
Thanks, I will give it a try.
Would you be interested in a PR that adds instructions about SublimeText to the README (in case it works) ?

**Comment by dan-t** [comment]
On Sun, Mar 08, 2015 at 10:45:16AM -0700, Sebastian Thiel wrote:
> Thanks, I will give it a try.
> Would you be interested in a PR that adds instructions about SublimeText to the
> README (in case it works) ?

Yes. :)

**Comment by Byron** [comment]
Shoot ! The Sublime Text Plugins wants a `rusty-tags.vi_sorted_by_file` file, which I just provided by copying the one Rusty creates. However, it will still fail with an uncaught error. The plugins quality doesn't seem to be too high, as it makes plenty of assumptions. Maybe it can, as it is able to run ctags itself (on request).

This can definitely be solved if I would adjust the Sublime plugin, but ... I don't want to open that box right now :).

Maybe another time, when I am desperate enough to really really need ctag support.
