### ISSUE TITLE
Don't throw error message if dependencies section is empty

### ISSUE THREAD

**Issue by pengowen123** [dan-t/rusty-tags#21]
A default `Cargo.toml` will include a `[dependencies]` section which has nothing in it. Running `rusty-tags vi` will throw the error: `Couldn't get Array of Table entries for 'package'!`. Removing this section makes the command run without errors, so it looks like it is a problem with having 0 dependencies.

**Comment by dan-t** [comment]
Should be now handled with `rusty-tags 0.7.0`.
