### ISSUE TITLE
go to definition not behaving correctly

### ISSUE THREAD

**Issue by kindlychung** [dan-t/rusty-tags#22]
Here is the code in question: https://github.com/kindlychung/stridist/blob/kindlychung-patch-1/src/main.rs#L43

If you put the cursor at `next` and then `c-]`, it will lead you to one of the testing functions, which is incorrect.

**Comment by dan-t** [comment]
You should be aware how `ctags` works, it just maps all `next` symbols to their source code location, have a look at the `rusty-tags.vi`, there're multiple entries for `next`, and `c-]` will just jump to
the first one and `:tnext` will go the next one.

`ctags` is really quite simple, but therefore easy to integrate in very editor.
