### ISSUE TITLE
Support for CARGO_HOME env variable?

### ISSUE THREAD

**Issue by DoumanAsh** [dan-t/rusty-tags#23]
I have CARGO_HOME variable to set it in non-default location so when i run rusty-tags:
```
Expected one matching path for 'C:\Users\Douman\.cargo\registry\src\github.com-*'!
```

Seems like rusty-tags is not able to pick up it from right directory?

p.s. why it is decided to not create tags in case of failing to find dependency?

**Comment by dan-t** [comment]
Should now be supported by rusty-tags 0.8.2.
