### ISSUE TITLE
Specify how to run this in background

### ISSUE THREAD

**Issue by antoyo** [dan-t/rusty-tags#25]
Hello.
It would be nice to specify how to run `rusty-tags` in the background, even though it is not specific to this plugin.

For instance, in `neovim`, the script would be the following:

```vim
setlocal tags=./rusty-tags.vi;/,$RUST_SRC_PATH/rusty-tags.vi

function! s:rustyTags()
    let cmd = "rusty-tags vi --start-dir=" . expand('%:p:h') . "&"
    call jobstart(cmd)
endfunction

autocmd BufWrite *.rs :silent call s:rustyTags()
```

I don't know how it must be written for `vim`, but I believe it will be similar.

Thanks.

**Comment by dan-t** [comment]
Hi antoyo,

> It would be nice to specify how to run rusty-tags in the background, even
> though it is not specific to this plugin.

I don't understand what you mean by this, because how rusty-tags is
called is up to the user by defining the 'autocmd BufWrite' appropriate.

Greetings,
Daniel

**Comment by antoyo** [comment]
Yes, I know. It is not a bug with this tool.

I meant it would be nice to add this script in the documentation so that `neovim` users can get the asynchronous behavior.
Buf if you think it does not belong to the vim configuration section of the `rusty-tags` readme, that's fine: just close this issue.

**Comment by dan-t** [comment]
Ok, if you would like to extend the README by a 'Neovim Configuration' section, then please go on
an create a pull request.
