### ISSUE TITLE
Cannot create rusty-tags.vim

### ISSUE THREAD

**Issue by kper** [dan-t/rusty-tags#26]
When I run `rusty-tags vi` in a project I get this output:
```
# rusty-tags vi
Fetching source of dependencies ...
No such file or directory (os error 2)
```

However, `rusty-tags emacs` works

Reproducing:
```
# cargo install rusty-tags
# cargo new test_project --bin
# rusty-tags vi
```

**Comment by dan-t** [comment]
On Fri, Jul 29, 2016 at 08:36:46AM -0700, kper wrote:
> When I run rusty-tags vi in a project I get this output:
> 
> # rusty-tags vi
> Fetching source of dependencies ...
> No such file or directory (os error 2)
> 
> However, rusty-tags emacs works
> 
> Reproducing:
> 
> # cargo install rusty-tags
> # cargo new test_project --bin
> # rusty-tags vi

MacOS? Please read the README.

**Comment by dan-t** [comment]
Can you please test `rusty-tags 0.9.1`, if you're getting a better error message?

**Comment by kper** [comment]
Sorry for not being clear. I am working on an ubuntu machine.

```
# rusty-tags vi
Fetching source of dependencies ...
ctags: unrecognized option '--recurse'
	Try `ctags --help' for a complete list of options.
```

I compiled ctags myself. It works now! Thanks
