### ISSUE TITLE
Specify output filename

### ISSUE THREAD

**Issue by W4RH4WK** [dan-t/rusty-tags#28]
Would be great to be able to specify the output file. I'd have to manually rename it every time after running rusty-tags.

**Comment by dan-t** [comment]
What I don't like about this option is, that it's harder to get vi and emacs tags
side by side, the user would have to be aware to use different names for the tags.

**Comment by dan-t** [comment]
Without fixed names it's also harder to detect for which format
tags have been already created.

What I might support is a configuration file where the vi and emacs tags
names have to be separatly defined.

**Comment by W4RH4WK** [comment]
I see your point, but don't most people just use one format (the one that fits their editor) and don't checkin the tagfile into their repository? A similar approach would be to have two output flags, one for vi and another for emacs tags.

**Comment by dan-t** [comment]
Well, at the end it's the difference between systems that just work and systems that don't.

Having output flags means that it might be easier to break the system by just calling:

    rusty-tags vi --vi-tags=TAGS

and

    rusty-tags emacs --emacs-tags=TAGS

A configuration file might encourage to make the decision once and reduce the risk
of breakage. Sure, the user could still change the configuration file for each run,
but this might be a bit less likely.

**Comment by dan-t** [comment]
I just pushed support for this.

It's not released yet, so you have to build from the repo, but the README is already up to date.

**Comment by W4RH4WK** [comment]
Great, thanks.

**Comment by dan-t** [comment]
It's out with rusty-tags 0.10.0
