### ISSUE TITLE
Absolute filepaths may cause issue

### ISSUE THREAD

**Issue by W4RH4WK** [dan-t/rusty-tags#29]
I tried using rusty-tags with Atom's [symbol-view](https://github.com/atom/symbols-view), which should be fine accepting ctag files. And while the dialog works in terms of searching for a symbol, the target file cannot be opened. I suspect this may be due to the absolute filepath in the tags file, which may not be non-standard.

Issue which lead me to this: atom/symbols-view#108

I'd suggest adding a flag for producing relative filepaths, so rusty-tags can be used with lesser-capable editors.

**Comment by dan-t** [comment]
It's somehow strange to say that the absolute paths in the vi tags format
a wrong when vi supports them. ;)

The tags for each library are cached and then merged together and I really
don't want to handle path conversions there.

That's the first time I'm hearing about such problems and I can't see why a tool
wouldn't support both, relative and absolute paths.
