### ISSUE TITLE
Do you have suggestions for vim -t support?

### ISSUE THREAD

**Issue by mqudsi** [dan-t/rusty-tags#37]
Thanks for making this awesome project. Do you have any suggestions for being able to open (n)vim and jump to a tag via the `-t tag_name` command line switch? Currently that throws an error about the tags file not being found.

Thanks!

**Comment by dan-t** [comment]
> Thanks for making this awesome project. Do you have any suggestions for being able to open (n)vim and jump to a tag via the -t tag_name command line switch? Currently that throws an error about the tags file not being found.
> 
Is the `:set tags` setting of vim pointing to the tags file created by `rusty-tags`?
Does calling `:tag tag_name` inside of vim work?

Greetings,
Daniel

**Comment by mqudsi** [comment]
Hi Daniel / @dan-t ,

Yup, it works great. I've been using `:tag tagname` with rusty tags very nicely.

**Comment by mqudsi** [comment]
I got everything working by configuring `rusty-tags vi` to emit to `./tags`, which is the default path for vim.

My updated configuration looks like this now:
```
autocmd BufWrite *.rs :silent! exec "!rusty-tags vi --quiet --start-dir=" . expand('%:p:h') . "&" <bar> redraw!
autocmd BufRead *.rs :setlocal tags=./tags;/,$RUST_SRC_PATH/rusty-tags.vi
```

**Comment by dan-t** [comment]
> I got everything working by configuring rusty-tags vi to emit to ./tags, which is the default path for vim.
> 
I can't quite follow you. With `:set tags` or `:setlocal tags` (for buffer local settings) you're
telling vim where to search for the tags file and how its named.

As long as the tags file name created by `rusty-tags` matches the one set by
`:setlocal tags` it should just work.

So, I don't understand your problem.

**Comment by mqudsi** [comment]
The problem is that you are relying on autocmd to call `:settag` for files matching *.rs
When you start vim without a file at all, jumping to a tag by name (`nvim -t some_tag`) it's not going to know to use the rust-specific tag extension and will use whatever the global default is.

By making rust share the global default tag file name, that problem is resolved.

**Comment by dan-t** [comment]
vim '+set ft=rust' -t tag_name

**Comment by dan-t** [comment]
> vim '+set ft=rust' -t tag_name

Hm, that one doesn't seem to work, but this one does:

    vim '+set ft=rust' -c ':tag Vec'

With this method also the tags for the rust standard library will work.
