### ISSUE TITLE
No generated file in library with only lib.rs

### ISSUE THREAD

**Issue by Ploppz** [dan-t/rusty-tags#38]
In a library with only `lib.rs` (specifically this https://github.com/pdf-rs/pdf_derive), `rusty-tags vi` doesn't generate any file.

**Comment by dan-t** [comment]
It's because `pdf_derive` only defines a procedural macro, so there aren't any symbols (structs, enums, functions, ...) defined which might be referenced by other crates.

**Comment by Ploppz** [comment]
I had hoped to jump around private functions in that library though (while developing it). Is it only in binary projects that private things get tagged?

**Comment by dan-t** [comment]
On Thu, Aug 31, 2017 at 05:36:28PM +0000, Erlend Langseth wrote:
> I had hoped to jump around private functions in that library though (while
> developing it). Is it only in binary projects that private things get tagged?

Ok, I've just pushed a change that should allow this with the current github version.

**Comment by Ploppz** [comment]
Great, thanks. When is does `cargo install` get the new version? It' not urgent for me, just wondering.

**Comment by dan-t** [comment]
`rusty-tags 2.2.0` is released.
