### ISSUE TITLE
CPU hungry

### ISSUE THREAD

**Issue by nyarly** [dan-t/rusty-tags#43]
I'm not sure how to provide better diagnostics than this, but for a moderately sized project (in terms of dependencies) rusty-tags consumes a lot of CPU - all 4 procs peg for about 2 minutes every time it's run. This isn't a huge deal, except when trying to use it as described in the README - to run on every save in Vim. Additionally, it seems to acquire a lock on the code files, so that `cargo` waits for it to complete.

Am I doing something wrong? Can I provide more information? My Cargo.toml looks like:
```
...
[dependencies]
error-chain = "^0.11"
tokio-tls = { version = "^0.1", features = ["tokio-proto"] }
tokio-core = "^0.1"
tokio-proto = "^0.1"
tokio-service = "^0.1"
futures = "^0.1"
hyper = "^0.11"
hyper-tls = "^0.1"
native-tls = "^0.1"
url = "^1.0"
uritemplate = "^0.1"
oauth2 = "^1.1"
rand = "^0.3"
base64 = "^0.7"
toml = "^0.4"
serde = "^1.0"
serde_derive = "^1.0"
```

**Comment by dan-t** [comment]
On Sat, Nov 11, 2017 at 08:38:12PM +0000, Judson Lester wrote:
> I'm not sure how to provide better diagnostics than this, but for a moderately
> sized project (in terms of dependencies) rusty-tags consumes a lot of CPU - all
> 4 procs peg for about 2 minutes every time it's run. This isn't a huge deal,
> except when trying to use it as described in the README - to run on every save
> in Vim. Additionally, it seems to acquire a lock on the code files, so that
> cargo waits for it to complete.

Counting all dependencies - also the indirect ones - your project has >80 dependencies.
So if there aren't already tags for them available, it's expected to take
some while for the first call.

I created an empty cargo project and added your dependencies.

The first call of `rusty-tags` forcing the creation of all dependencies:

    dan@octa ~/test/cargo/foo [master #%]> time rusty-tags vi --force-recreate
    Fetching source and metadata ...
    Creating tags for the standard library ...
    Creating tags for 'foo' ...
    
    real    11m13.955s
    user    8m5.716s
    sys     2m21.640s

The second call of `rusty-tags` using the cached tags:

    dan@octa ~/test/cargo/foo [master #%]> time rusty-tags vi
    Fetching source and metadata ...
    Creating tags for 'foo' ...
    
    real    0m1.275s
    user    0m1.036s
    sys     0m0.224s

As long as the cached variant is that fast I really don't see the need for any
kind of further optimization.

**Comment by nyarly** [comment]
I went to respond to this, initially only to find that my timing results are the same as yours - rusty-tags vi runs in less than a second. And the trouble I was having with rusty-tags being a BufWrite autocommand seemed covered.

But, just now, I observed the same phenomenon: I saved a code file in rust, only to see my CPUs peg for about a minute, and 80+ rusty-ctags processes were running. (They're still running, actually...)

Is it possible that the tags files are getting clobbered somehow? I'm not sure I have another explanation for this.

**Comment by nyarly** [comment]
As they're still running: `pgrep rusty | wc -l` => 1586 (:surprised:)

**Comment by dan-t** [comment]
You can't reproduce it from the command line, right?
You aren't using the option `--force-recreate`?
Are you saving a lot of rust files at once?

**Comment by dan-t** [comment]
If you can reproduce it from the command line, then try it with the `--verbose` flag.

**Comment by dan-t** [comment]
> As they're still running: pgrep rusty | wc -l => 1586 (!!!)

`rusty-tags` doesn't create multiple threads by itself, but the invocation of `ctags` does, so if you're seeing that much `rusty-tags` processes, then your editor has invoked `rusty-tags` that often.

**Comment by dan-t** [comment]
Have you solved your issue?

The current github version now uses multiple threads for the tags creation,
which speeds up the creation quite a bit for your example dependencies.

**Comment by edelangh** [comment]
Hi !
I've got the same issue. rusty-tags take minutes on my project every time
```
[~/work]$ time /tmp/rusty-tags/target/release/rusty-tags --quiet vi --start-dir .                     *[dev] 
/tmp/rusty-tags/target/release/rusty-tags --quiet vi --start-dir .  79.97s user 26.76s system 99% cpu 1:47.08 total
[~/work]$ time /tmp/rusty-tags/target/release/rusty-tags --quiet vi --start-dir .                     *[dev] 
/tmp/rusty-tags/target/release/rusty-tags --quiet vi --start-dir .  41.95s user 17.95s system 99% cpu 1:00.23 total
```
Could we simply prevent new rusty from running?

Using:
 - Use file lock; we check if file lock exist, if it does we return, else we create lock file and delete it at end.
 - In main we could check if existing rusty run, check if /proc/../cmdline match and return if it does

Do you want PR with one of this?

**Comment by dan-t** [comment]
Hi,

there's already a per cargo project lock file. Checking `/proc` isn't an option, because that's platform dependent.

What is the output with the `--verbose` flag? I never saw this behavouir on my machines, so it's a bit hard to debug. Is the cargo project with the issue public? Do you've the issue with different cargo projects?

Greetings,
Daniel

**Comment by edelangh** [comment]
Hi dan !

Thank you for helping.
https://drive.google.com/file/d/1OlZWb9-zwIpFqAkmM4GYymVdlWC_kAcF/view?usp=sharing
Here the trace with --verbose

I'm using workspace
```
[workspace]                                                                                                           
members = [ "ai", "bbfs", "core", "meta_cache", "rust-fuse", "settings", "server" 
```
Do you think this can multi exponentially the scan ?

**Comment by dan-t** [comment]
Hi,

> https://drive.google.com/file/d/1OlZWb9-zwIpFqAkmM4GYymVdlWC_kAcF/view?usp=sharing
> Here the trace with --verbose

it looks quite normal, nothing spezial. So for every call of `rusty-tags`
on this cargo project you're getting the same output with `--verbose`?

Is the cargo project public? Where can I find it? 
If not, can you give me the `[dependencies]` section from the `Cargo.toml`?

> I'm using workspace
> 
> [workspace]
> members = [ "ai", "bbfs", "core", "meta_cache", "rust-fuse", "settings", "server"
> 
> Do you think this can multi exponentially the scan ?

I don't think so. It should just create the tags for every member
of the workspace.

Greetings,
Daniel

**Comment by edelangh** [comment]
It isn't public.

Here the Cargo.lock with all dependencies and versions for all Cargo.toml I have
https://drive.google.com/file/d/1tfEiY6zN8ZWyJpXso93e-OuoBWBO6F0l/view?usp=sharing

And yes same verbose each time ...

BTW:
```
[~/work]$ rusty-tags --version                                                                                                                                                                                                *[dev] 
rusty-tags 2.10.0
```

**Comment by dan-t** [comment]
I've extended the output of '--verbose'. So can you please build
the current github version of 'rusty-tags', call it with '--verbose'
and send me the output.

**Comment by dan-t** [comment]
Do you still have the issue?

**Comment by edelangh** [comment]
Yes! I'm sorry, I didn't see your last message.

I'm will send you logs with new verbose tomorrow.

**Comment by edelangh** [comment]
Hii !

I've new very strange logs.

rusty-tags: run 3times with differents duration and output:
```
[~/work/MyProject]$ rusty-tags --version 
rusty-tags 2.11.0
[~/work/MyProject]$ time rusty-tags --verbose vi --start-dir . > /tmp/log1.txt
rusty-tags --verbose vi --start-dir . > /tmp/log1.txt  54.90s user 22.92s system 99% cpu 1:18.24 total
[~/work/MyProject]$ time rusty-tags --verbose vi --start-dir . > /tmp/log2.txt
rusty-tags --verbose vi --start-dir . > /tmp/log2.txt  225.74s user 104.73s system 99% cpu 5:32.36 total
[~/work/MyProject]$ time rusty-tags --verbose vi --start-dir . > /tmp/log3.txt 
rusty-tags --verbose vi --start-dir . > /tmp/log3.txt  37.23s user 15.41s system 99% cpu 53.066 total
[~/work/MyProject]$ ls -lah /tmp/log*.txt 
-rw-r--r-- 1 rico users 106M Oct 15 13:20 /tmp/log1.txt
-rw-r--r-- 1 rico users 400M Oct 15 13:26 /tmp/log2.txt
-rw-r--r-- 1 rico users  70M Oct 15 13:27 /tmp/log3.txt
```

Timing wtf:
```
[~/work/MyProject]$ for I in ai bbfs core meta_cache provider rust-fuse server settings ; do echo $I ; time rusty-tags --verbose vi --start-dir $I > /tmp/log6$I.txt;done 
ai
rusty-tags --verbose vi --start-dir $I > /tmp/log6$I.txt  27.83s user 16.24s system 98% cpu 44.767 total
bbfs
rusty-tags --verbose vi --start-dir $I > /tmp/log6$I.txt  253.52s user 112.76s system 99% cpu 6:09.44 total
core
rusty-tags --verbose vi --start-dir $I > /tmp/log6$I.txt  20.65s user 10.59s system 99% cpu 31.437 total
meta_cache
rusty-tags --verbose vi --start-dir $I > /tmp/log6$I.txt  21.70s user 9.48s system 99% cpu 31.301 total
provider
rusty-tags --verbose vi --start-dir $I > /tmp/log6$I.txt  61.43s user 24.60s system 99% cpu 1:26.44 total
rust-fuse
rusty-tags --verbose vi --start-dir $I > /tmp/log6$I.txt  232.75s user 106.17s system 99% cpu 5:41.32 total
server
rusty-tags --verbose vi --start-dir $I > /tmp/log6$I.txt  62.76s user 25.42s system 99% cpu 1:28.64 total
settings
 rusty-tags --verbose vi --start-dir $I > /tmp/log6$I.txt  425.19s user 191.07s system 99% cpu 10:20.44 total
```

Some weight info:
```
[~/work]$ du -d1 -h ~/.cargo 
1.1G	/home/edelangh/.cargo
[~/work/MyProject]$ du -d1 -h ~/work/MyProject
1.1G	/home/edelangh/work/MyProject
[~/work/MyProject]$ cargo clean 
[~/work/MyProject]$ du -d1 -h . 
201M	.
```

files log
https://drive.google.com/open?id=11C_ujOckU1YcH_uUdJuAK8nu7CpO0IdG

**Comment by dan-t** [comment]
Hi,

log2.txt and log3.txt are what I would expect from calling 'rusty-tags'
a second time on a cargo project with already created tags:

Rebuilding tags for cargo project root 'ai'
Rebuilding tags for cargo project root 'bbfs'
Rebuilding tags for cargo project root 'settings'
Rebuilding tags for cargo project root 'core'
Rebuilding tags for cargo project root 'cache'
Rebuilding tags for cargo project root 'fuse'
Rebuilding tags for cargo project root 'provider'
Rebuilding tags for cargo project root 'server'
Rebuilding tags for cargo project root 'fantafs'

All these cargo projects are part of a workspace and the tags for all
these projects are recreated for every call of 'rusty-tags'. The whole
optimization and caching is only done for the tags of the dependencies.

Could you time the call of 'ctags' on the whole workspace? If it takes
the same time then calling 'rusty-tags', then this seems to be the issue,
that recreating the tags for the whole workspace is quite costly.

Most likely the easiest optimization in this case would be to use the
directory of '--start-dir' has a hint which project of the workspace has
been modified and only recreating the tags for this project.

Grettings,
Daniel

**Comment by edelangh** [comment]
```
[~/work/MyProject]$ time ctags --languages=+Rust **/*.rs
ctags --languages=+Rust **/*.rs  0.30s user 0.05s system 99% cpu 0.344 total
[~/work/MyProject]$ time ctags --languages=+Rust **/*.rs ~/.cargo/**/*.rs
ctags --languages=+Rust **/*.rs ~/.cargo/**/*.rs  16.91s user 0.76s system 91% cpu 19.324 total
[~/work/MyProject]$ time ctags --languages=+Rust **/*.rs ~/.cargo/**/*.rs 
ctags --languages=+Rust **/*.rs ~/.cargo/**/*.rs  16.76s user 0.57s system 99% cpu 17.474 total
```

**Comment by dan-t** [comment]
Hi,

> [~/work/MyProject]$ time ctags --languages=+Rust **/*.rs
> ctags --languages=+Rust **/*.rs  0.30s user 0.05s system 99% cpu 0.344 total

ok, then the tags creation for the whole workspace doesn't seem to be the issue.

Could you profile the 'rusty-tags' executation with 'valgrind':
   valgrind --tool=callgrind rusty-tags vi

And send me the 'callgrind.out.<pid>' file.

Greetings,
Daniel

**Comment by dan-t** [comment]
The current github version should now fix the biggest issues:

    dan@octa ~/test/cargo/MyProject> time rusty-tags vi
    Fetching source and metadata ...
    Creating tags for 'ai' ...
    Creating tags for 'bbfs' ...
    Creating tags for 'settings' ...
    Creating tags for 'core' ...
    Creating tags for 'cache' ...
    Creating tags for 'fuse' ...
    Creating tags for 'provider' ...
    Creating tags for 'fantafs' ...

    real    0m0.515s
    user    0m0.304s
    sys     0m0.192s

**Comment by edelangh** [comment]
WTF ! It's so fast now !!!
And it's work !!!
```
[~/work/MyProject]$ time /tmp/rusty-tags/target/release/rusty-tags --verbose vi --start-dir . > /tmp/log5.txt
/tmp/rusty-tags/target/release/rusty-tags --verbose vi --start-dir . >   0.44s user 0.46s system 121% cpu 0.743 total
```

Thank you !!

**Comment by dan-t** [comment]
I've added a few other optimizations, so even a '--force-recreate' should now be quite fast.
All of this is now release in 'rusty-tags 3.0.0'.

Thanks for the test example!
