### ISSUE TITLE
Specify output directory

### ISSUE THREAD

**Issue by nyarly** [dan-t/rusty-tags#44]
I'm using NixOS, so the natural way to get and update my rust source directory involves installing it to a read-only filesystem. It'd be keen, therefore, to be able to tell rusty-tags to write its tag file, as opposed to into the root of the rustlib source.

I could probably produce a PR for this, if that'd help.

**Comment by dan-t** [comment]
On Sat, Nov 11, 2017 at 08:40:23PM +0000, Judson Lester wrote:
> I'm using NixOS, so the natural way to get and update my rust source directory
> involves installing it to a read-only filesystem. It'd be keen, therefore, to
> be able to tell rusty-tags to write its tag file, as opposed to into the root
> of the rustlib source.

It won't really work that way, because then all tags files will be put
into one directory. `rusty-tags` puts a tags file at the root
of each dependency, which is necessary that the editor will find the
right tags file for each cargo project.

What's your use case? Putting your sources into a read-only filesystem
means you can't modify them, so you're not developing the project. But
why do need tags then? Just for reading the source?

**Comment by nyarly** [comment]
The tags I'm interested in are for the rust stdlib - i.e. what rusty-tags
looks to when $RUST_SRC_LIB is set. No, I don't intend to edit them, but
reference and completion would be a huge boon.

I wouldn't want to set a global configuration for the output - but a
command line switch to output the tags for stdlib once and then point vim
to that file (e.g. somewhere in my homedir. Or, I've already opened an
issue with Nix to create a package just for tags of the stdlib.)

**Comment by dan-t** [comment]
That's a very special use case.

If you want tags only for the Rust source code you can just the ctags specification contained in the Rust source:

    ctags -f tags --options=/path/to/rust/src/etc/ctags.rust --recurse /path/to/rust/src

**Comment by dan-t** [comment]
Are you aware, if you're using `rustup` for getting the rust sources - like described in the README - then automatically the right tags for the currently used Rust version are created?

**Comment by nyarly** [comment]
Ultimately, I'd like to be using Nix to manage my Rust dev environment, though, so relying on rustup is a non-starter.

**Comment by dan-t** [comment]
If you can't put the tags file at the root of the sources, then you won't have a development environment where you can easily switch compiler versions without having to reconfigure your vim settings.

Nix certainly has nice properties, but I can't see its advantage in this particular use case.

**Comment by nyarly** [comment]
There's some work to integrate most-current Rust into the Nix tree, at while point I'm pulling for a generated ctags file to be added as well - either to the sources themselves or in a separate package. Once that's done, nix-shell will be usable to switch between Rust versions per-project.
