### ISSUE TITLE
Supprort XDG-DIRS for storing information

### ISSUE THREAD

**Issue by darnir** [dan-t/rusty-tags#47]
Could you please add support for the `$XDG_DATA_HOME` and `$XDG_CONFIG_HOME` environment variables instead of hard-coding "~/.rusty-tags" as the directory for storing data in?

**Comment by dan-t** [comment]
I'm not interested in doing platform specific things and doing it platform independet isn't that straight forward.

You also have to think about backward combatibility of configuration files.

So it's more work than it might look.
