### ISSUE TITLE
Fails on linux

### ISSUE THREAD

**Issue by Opioid** [dan-t/rusty-tags#59]
When I try to generate tags for a rust project on linux I get the following error message. (FWIW it worked on a windows machine)

> rusty-tags emacs
> Fetching source and metadata ...
> Creating tags for: ["bud"] ...
> thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Message("ctags: invalid option -- \'e\'\n\tTry \'ctags --help\' for a complete list of options.\n")', src/libcore/result.rs:997:5
> note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
> thread 'main' panicked at 'Thread pool worker panicked', /home/beni/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.9/src/lib.rs:236:13

**Comment by dan-t** [comment]
Has the ctags executable an option -e?

**Comment by Opioid** [comment]
Sorry, I messed something up with my ctags program. All is in order after further investigation. Thanks!

**Comment by trissylegs** [comment]
Ran into same issue cause emacs ctags was in my PATH ahead of ctags.
Which doesn't support `-e`.
