### ISSUE TITLE
Support  for rust core

### ISSUE THREAD

**Issue by danielakhterov** [dan-t/rusty-tags#61]

**Comment by dan-t** [comment]
I really need a bit more information.

**Comment by danielakhterov** [comment]
I'm following Phil Opperman's Blog OS, and rusty-tags works great for almost everything except things under core. For instance when attempting to follow `&PanicInfo` located under `use core::panic::PanicInfo;` I get a "tag could not be found".

**Comment by dan-t** [comment]
> For instance when attempting to follow &PanicInfo located under use core::panic::PanicInfo; I get a "tag could not be found".

I can't reproduce this. `PanicInfo` is contained in the tags file under `$RUST_SRC_PATH/rusty-tags.vi` or  `$RUST_SRC_PATH/rusty-tags.emacs`.

Are you sure that your editor is using the tags file under `$RUST_SRC_PATH`. The tags for the rust std are NOT automatically contained in the tags file of the cargo project.

**Comment by danielakhterov** [comment]
It was my mistake. I thought the rust source ctags file was automatically contained. As soon as I added the rust source tags file everything works. Thanks!
