### ISSUE TITLE
[feature request] Flag for skipping impls

### ISSUE THREAD

**Issue by osa1** [dan-t/rusty-tags#66]
Currently if I have a `struct Foo { ... }` and `impl Foo { ... }`, rusty-tags generates two tags for `Foo`, one for the type definition, another one for the impl. Most of the time unless I'm looking for a function I only want type definitions, so a flag for omitting impls would be helpful.

**Comment by dan-t** [comment]
On Tue, Dec 03, 2019 at 06:24:21AM -0800, Ömer Sinan Ağacan wrote:
> Currently if I have a struct Foo { ... } and impl Foo { ... }, rusty-tags generates two tags for Foo, one for the type
> definition, another one for the impl. Most of the time unless I'm looking for a function I only want type definitions,
> so a flag for omitting impls would be helpful.

You can get it by adding `ctags_options = "--Rust-kinds=-c"` to your config.

At the end it's about the ctags options and I don't want a separate flag
for them or having to deal with the merging of flags and the config.

But I would be fine if you create a pull request for adding a command
line argument for the ctags options.
