### ISSUE TITLE
stdlib instructions are not compatible with the MacOS version of ctags

### ISSUE THREAD

**Issue by contradictioned** [dan-t/rusty-tags#7]
MacOS users cannot tag the standard library unless they get another Ctags version,
e.g. how described here: http://gmarik.info/blog/2010/10/08/ctags-on-OSX

If you want this to be added to the readme I can write a sentence and a PR; if not, I just leave this here for future reference ;)

**Comment by dan-t** [comment]
> If you want this to be added to the readme I can write a sentence and a PR ...

Yes please!


Greetings,
Daniel
