### ISSUE TITLE
rusty-tags blocks vim ~5 seconds when :w executes in a very large project

### ISSUE THREAD

**Issue by w93163red** [dan-t/rusty-tags#71]
Hi,

I use rusty-tags for a while. It is a wonderful plugin. But recently I found that every time when I execute ":w", the vim will hang for few seconds. Is there anyway to execute the refresh tags file in async way?

![image](https://user-images.githubusercontent.com/7308728/86162204-6fd4a600-badc-11ea-8d56-c13fa8b9e57a.png)

**Comment by dan-t** [comment]
Hi,

how does the autocomand in the vimrc for executing rusty-tags look?
If it ends with a &, then it should be executed in the background.

Greetings,
Daniel

**Comment by w93163red** [comment]
> Hi, how does the autocomand in the vimrc for executing rusty-tags look? If it ends with a &, then it should be executed in the background. Greetings, Daniel

Hi Daniel, 

Thanks for the quick reply. I just copied the autocmd from the README.md.

**Comment by dan-t** [comment]
> Thanks for the quick reply. I just copied the autocmd from the README.md.

I‘m not quite sure if the „| redraw!“ at the end might prevent the background execution, so try removing it.

Otherwise how big is the tags file? Perhaps reloading it takes some time. How long does it take to start vim when the tags file is already present?

**Comment by w93163red** [comment]
> I‘m not quite sure if the „| redraw!“ at the end might prevent the background execution, so try removing it. Otherwise how big is the tags file? Perhaps reloading it takes some time. How long does it take to start vim when the tags file is already present?

I have removed the redraw but it does not help.  The overall tags file close to 100M. When starting vim, I did not feel any latency .

**Comment by w93163red** [comment]
I tried to use asyncrun. But it does not help. Vim will not allow me to type anything.

**Comment by dan-t** [comment]
Seems strange, I never had issues with executing a command in the
background with '&'.

Perhaps it's a issue similar to: https://superuser.com/questions/550035/vim-execute-process-in-background

**Comment by w93163red** [comment]
I have switched to vim-gutentags. It seems to solve the problem. I will keep testing today.

**Comment by dan-t** [comment]
Can you test any other longer running external command with ':!command &',
to test if vim behaves in the same way.

If that's the case, then for whatever reasons the background execution
with '&' doesn't work.

**Comment by dan-t** [comment]
On Wed, Jul 01, 2020 at 03:32:46PM +0200, Daniel Trstenjak wrote:
> Can you test any other longer running external command with ':!command &',
> to test if vim behaves in the same way.

There's a 'silent' missing: ':silent !command &'

**Comment by w93163red** [comment]
will do. BTW, i am using neovim.

Daniel Trstenjak <notifications@github.com> 于2020年7月1日周三 上午9:37写道：

**Comment by dan-t** [comment]
Anything new about the background command execution?

**Comment by w93163red** [comment]
Currently I think I will close it. The background stuff runs fine. It did
not hang any more.

Daniel Trstenjak <notifications@github.com> 于2020年7月17日周五 下午2:12写道：
