### ISSUE TITLE
Broken feature omit dependencies

### ISSUE THREAD

**Issue by UnkwUsr** [dan-t/rusty-tags#73]
That was broken here: https://github.com/dan-t/rusty-tags/commit/0d7a33d4921f3cd60d253da2b7ceb80dbb8b4149#diff-b296903f197dacaca021f7e757a588e6L58

P.S. Of course, thanks for good project :D

**Comment by dan-t** [comment]
I commited a fix. Please test!

**Comment by UnkwUsr** [comment]
All works good. Thanks!
