### ISSUE TITLE
Does not find dependencies in Fedora (32) for emacs

### ISSUE THREAD

**Issue by admiyo** [dan-t/rusty-tags#74]
Generating the code for emacs only finds the code in the current directory.  VI version seesm to find depdencies OK in the cargo cache.

cargo install rusty-tags
rusty-tags emacs  
$ wc -l rusty-tags.emacs 
30 rusty-tags.emacs
$ wc -l rusty-tags.vi 
1023 rusty-tags.vi

Cannot browse into dependencies with emacs

vi generated tags work correctly

**Comment by dan-t** [comment]
Hi Adam,

does the emacs tags file have include lines for the dependencies?
Does your emacs tags plugin support these include lines?

Greetings,
Daniel

**Comment by admiyo** [comment]
I've generated the file with both exuberant and the etags that comes 
with the emacs RPM.  No difference.

The rusty-tags.emacs file does have the include lines.   Those files are 
there and are generated.  I am guessing the emacs is just being dumb.


$ cat rusty-tags.emacs


/home/ayoung/devel/rust/rustboot/src/dhcp.rs,1403
...

/home/ayoung/.rusty-tags/cache/clap-9937940079245099657.emacs,include
/home/ayoung/.rusty-tags/cache/mac_address-220633793486163585.emacs,include
/home/ayoung/.rusty-tags/cache/num-7472547175417462205.emacs,include
/home/ayoung/.rusty-tags/cache/num-traits-495207980669005113.emacs,include

The firstone, clap, pulls in a lot of other dependencies, and those are 
not generated in the file listed above.  Is Cargo recursion not working?

**Comment by dan-t** [comment]
> The firstone, clap, pulls in a lot of other dependencies, and those are 
> not generated in the file listed above.  Is Cargo recursion not working?

The cargo project tags file only contains the direct dependencies. Each dependency gets put a tags file into its source directory inside of „.cargo“. So for clap inside of this tags file it should include its dependencies.

The point behind this is, that you only get the tags that are reachable from your current source file, and therefore reducing the collision of equally named tags.

**Comment by admiyo** [comment]
Anything not defined with the project is not found.  MacAddress and 
clap::Args are both in the Cargo.toml file, and you can see the includes 
above, but "No defintinons found for: MacAddress" and so on.

It looks like it is not expandind the included dependencies in the local 
tags file.

**Comment by dan-t** [comment]
> It looks like it is not expandind the included dependencies in the local 
> tags file.

Ok, then it looks like this is the case.

Have you tried the emacs tags plugin mentioned in the readme? This one should support the include lines.

**Comment by admiyo** [comment]
Will close, as it seems to be the Tags generation, and not rusty-tags
