### ISSUE TITLE
Out of memory recursing large rust project

### ISSUE THREAD

**Issue by wzli** [dan-t/rusty-tags#83]
Maybe intermittently save tags to disk instead of storing all in memory until the end. When program gets killed after out of memory the locks have to be manually cleared which is slightly annoying as well. I have 32GB installed so that already decently hefty.

**Comment by dan-t** [comment]
Without more details, how many dependencies the project has, how the dependency tree looks and where at all that much memory gets used, there‘s nothing I can do. Because it isn’t at all obvious, why that much memory should be used.

**Comment by dan-t** [comment]
Try the option ‘-n 1’ to reduce the number of threads and memory consumption. With the option ‘-v’ information about the tags creation is printed out and might help me to diagnose the issue.

**Comment by wzli** [comment]
Hi, I could not reproduce the issue on the v3.9.0. It only happen on the v3.5.1 that came with Ubuntu distribution. Here's the logs generated from running -n 1 -v though.
[log.txt](https://github.com/dan-t/rusty-tags/files/7575620/log.txt)
