### ISSUE TITLE
Error detected while processing BufRead Autocommands for "*.rs"..FileType Autocommands for "*"..function <SNR>15_LoadFTPlugin:

### ISSUE THREAD

**Issue by fancywriter** [dan-t/rusty-tags#85]
This is happening while I am trying to navigate back (CTRL + O) after going to any Rust definition. I am seeing the following error:
```
Error detected while processing BufRead Autocommands for "*.rs"..FileType Autocommands for "*"..function <SNR>15_LoadFTPlugin:
line    2:
E1126: Cannot use :let in Vim9 script
```
What could be a reason for it?

I have added two lines as in README to ~/.vimrc
```
autocmd BufRead *.rs :setlocal tags=./rusty-tags.vi;/,$RUST_SRC_PATH/rusty-tags.vi
autocmd BufWritePost *.rs :silent! exec "!rusty-tags vi --quiet --start-dir=" . expand('%:p:h') . "&" | redraw!
```

Vim version
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 22 2022 14:34:34)
Included patches: 1-4328
Modified by Gentoo-8.2.4328-r1
```

Not 100% sure it relates to the tags, could it be that I misconfigured something?
I also use rust.vim plugin https://github.com/rust-lang/rust.vim

**Comment by dan-t** [comment]
Looks like a vim bug:
https://groups.google.com/g/vim_dev/c/KjriETdrooI?pli=1

**Comment by fancywriter** [comment]
Indeed, upgrading to vim-8.2.4586 helped. Thanks and sorry for disturbing. Looks like it indeed is not related (directly) to Rust. Weird that it wasn't reproducible with other languages...
