### ISSUE TITLE
Dead link in README for ctags on macOS.

### ISSUE THREAD

**Issue by bicarlsen** [dan-t/rusty-tags#89]
In the MacOS Issues section of the README there is a [dead link to an article](https://github.com/dan-t/rusty-tags/blob/cc1112de809cb04f17abb7f5ca05fab5f9376663/README.md?plain=1#L132). The new URL of the post is https://www.gmarik.info/blog/2010/ctags-on-osx/.

**Comment by dan-t** [comment]
Is now fixed.
Thanks!
