### ISSUE TITLE
ctrl-] looks for a tags file

### ISSUE THREAD

**Issue by aidylewis** [dan-t/rusty-tags#9]
'rusty-tags vi' creates a 'rusty-tags.vi', however when I use 'ctrl-]', vi looks for a tags file. When I create a tags file 'ctags -R .', the function definition is not found. 

The project has been built with Cargo.

**Comment by dan-t** [comment]
Have you read the `Vim Configuration` section of the README?

**Comment by aidylewis** [comment]
Good man.
