### ISSUE TITLE
Couldn't extract version from id: 'registry+https://github.com/rust-lang/crates.io-index#actix-codec@0.5.1'

### ISSUE THREAD

**Issue by k-bx** [dan-t/rusty-tags#90]
Getting this error:

```
$ rusty-tags --version
rusty-tags 3.10.0
$ just tags
rm TAGS || true
rm: TAGS: No such file or directory
rusty-tags -s ./project emacs
Fetching source and metadata ...
Couldn't extract version from id: 'registry+https://github.com/rust-lang/crates.io-index#actix-codec@0.5.1'

error: Recipe `tags` failed on line 66 with exit code 1
```

**Comment by dan-t** [comment]
Hi Kostia,

> Fetching source and metadata ...
> Couldn't extract version from id: ***@***.***'

I'm expecting from 'cargo metadata --format-version=1' an id in the format:
   'actix-codec 0.5.1 (registry+https://github.com/rust-lang/crates.io-index)'

Which cargo/rustc versions are you using?

It looks like cargo changed its metadata format regardless of the version.

Greetings,
Daniel

**Comment by k-bx** [comment]
Hi Daniel

```
$ cargo --version
cargo 1.78.0-nightly (8964c8ccf 2024-02-27)
$ rustc --version
rustc 1.78.0-nightly (c475e2303 2024-02-28)
```

**Comment by dan-t** [comment]
Is now fixed with v3.11.0.

**Comment by sustainablelab** [comment]
I'm having a similar problem:
```
$ rusty-tags vi                                                                                                                                                                                                                      
Fetching source and metadata ...                                                                                                                                                                                                               
Couldn't extract version from id: 'registry+https://github.com/rust-lang/crates.io-index#aes@0.8.4' 
```
```
$ cargo --version                                                                                                                                                                                                                    
cargo 1.79.0 (ffa9cf99a 2024-06-03)                                                                                                                                                                                                            
$ rustc --version                                                                                                                                                                                                                    
rustc 1.79.0 (129f3b996 2024-06-10) 
```

**Comment by dan-t** [comment]
On Mon, Jul 08, 2024 at 07:59:56PM -0700, sirdigby wrote:
> I'm having a similar problem:
> ```
> $ rusty-tags vi                                                                                                                                                                                                                      
> Fetching source and metadata ...                                                                                                                                                                                                               
> Couldn't extract version from id: ***@***.***' 
> ```
> ```
> $ cargo --version                                                                                                                                                                                                                    
> cargo 1.79.0 (ffa9cf99a 2024-06-03)                                                                                                                                                                                                            
> $ rustc --version                                                                                                                                                                                                                    
> rustc 1.79.0 (129f3b996 2024-06-10) 
> ```

I'm pretty sure you're not using the newest version of rusty-tags (v3.11.0).
Please update your rusty-tags command.

**Comment by sustainablelab** [comment]
I am having the same issue.

```
$ rusty-tags vi
Fetching source and metadata ...
Couldn't extract version from id: 'registry+https://github.com/rust-lang/crates.io-index#actix@0.13.5'

$ cargo --version
cargo 1.82.0 (8f40fc59f 2024-08-21)
$ rustc --version
rustc 1.82.0 (f6e511eec 2024-10-15)
```

I am using the latest commit of `rust.vim`:
```
889b9a7515db477f4cb6808bef1769e53493c578 pack/bundle/start/rust.vim (heads/master)
```

I update rusty-tags by pulling the latest from `https://github.com/rust-lang/rust.vim`, right? Is there some other way to update the rusty-tags command that I am missing?

**Comment by dan-t** [comment]
Hi sirdigby,

> I update rusty-tags by pulling the latest from `https://github.com/rust-lang/rust.vim`, right? Is there some other way to update the rusty-tags command that I am missing?
> 

you're getting the newest version of rusty-tags from 'https://github.com/dan-t/rusty-tags' and building it with cargo.

Greetings,
Daniel

**Comment by dan-t** [comment]
> you're getting the newest version of rusty-tags from 'https://github.com/dan-t/rusty-tags' and building it with cargo.

Actually, because the newest version of rusty-tags is already released
at 'crates.io', you can just run 'cargo install rusty-tags' and
automatically get the newest version. The build rusty-tags is then
located at '~/.cargo/bin'.

**Comment by sustainablelab** [comment]
Thank you! I now have Rust tags in Vim!

`cargo install rusty-tags` and then `rusty-tags vi` inside the Rust project.

It is too bad that https://github.com/dan-t/rusty-tags is not listed on the Rust-lang getting started website https://www.rust-lang.org/learn/get-started. That page has a Vim link that goes to https://github.com/rust-lang/rust.vim. Perhaps the README at that repo should mention https://github.com/dan-t/rusty-tags.
