### ISSUE TITLE
Incomplete tag generation

### ISSUE THREAD

**Issue by matthewmturner** [dan-t/rusty-tags#92]
Im getting very hit or miss results with the generated tags in my project.

for example i have these imports but the only one that works where i can go to the tag is `arrow_schema::DataType`.  When i check the tag file most of the imports from datafusion arent there so its not really suprising that they dont work (for example the word `Volatility` isnt  in the file at all).  Am i misunderstanding how tags work?

<img width="751" alt="image" src="https://github.com/user-attachments/assets/97a107e2-688a-4958-8aaf-d08acee688ab">

**Comment by dan-t** [comment]
Hi Matthew,

how are the symbols of datafusion defined/exported? There‘re cases that ctags doesn‘t understand, like exports from internal modules.

Greetings,
Daniel

**Comment by matthewmturner** [comment]
Hi Daniel - thanks for the response.  I wasnt aware that ctags doesnt understand exports from internal modules - i believe thats what they are.  Do you know of any work arounds?

**Comment by dan-t** [comment]
Hi Matthew,

if the internal modules aren’t located in the source directory of the package, then ctags can‘t find the symbol definitions. That are the limits of a regex based tagger and only a language aware tagger could solve the problem.

Greetings,
Daniel
